#!/bin/sh

# Dependencies - webtorrent, mpv ,rofi or fzf
# Optional Dependencies - rg

RED='\033[1;31m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORM=$(tput sgr0)

baseurl="https://1337x.to"
# greping_tool="grep"
greping_tool="rg"
notflix(){
	RAW="$(curl -s "$baseurl/search/$query/1/")"

	titles="$(echo "$RAW" | $greping_tool "<a href=\"/torrent/.*</a>" | sed "s/<[^>]*>//g")"
	[ -z "$titles" ] && notify "Exiting" "No Results found for \"$(echo $query | tr "+" " ")\"" && exit
	size="$(echo "$RAW" | $greping_tool "<td class=\"coll-4 size.*</td>" | sed "s/<span class=\"seeds\">.*<\/span>//g" |sed -e 's/<[^>]*>//g'  )"
	links="$(echo "$RAW" | $greping_tool "/torrent/" | sed -E 's#.*(/torrent/.*)/".*#\1#')"
	list="${titles}${size}"
	selected="$(echo "$list" | pr -J -2 -t --length="$(echo "$titles" | wc -l)" --sep-string=" : " |nl -s: -w1 | $menu | cut -d: -f1)"
	[ -z "$selected" ] && notify "Exiting" "No Results selected for \"$(echo $query | tr "+" " ")\"" && exit
	notify "Loading" "\"$(echo $query | tr "+" " ")\" will be ready for viewing in just a second!"
	magnetURL="${baseurl}$(echo "$links" | sed -n "${selected}p")/"
	magnet="$(curl -s "$magnetURL" | $greping_tool "magnet:\?xt=urn:btih:" | sed "s#.*href=\"\(magnet:?xt=urn:btih:.*\)\" o.*#\1#" | head -n 1)"
	webtorrent "$magnet" --mpv
}

if [ -t 1 ] ; then

	menu="fzf"
	notify(){
		echo -e "${RED}${BOLD}${1}: ${NORM}${NC} ${2}"
	}
	echo -n "${BOLD}Movie: ${NORM}"
	read -r query
	query="$(echo "$query" | tr " " "+")"
else

	menu="rofi -dmenu -i -l 5 -p  -format d -matching normal "
	notify(){
		notify-send "${1}" "${2}" -i NONE
	}
	search_menu="rofi -dmenu -i -p Anime:"
	query="$($search_menu | tr " " "+")"
fi

notflix
